Export update + QOL
General:
+description thing now in seperate file
+utmp now knows where it is when running
+Reset the trap behavior before the program exits so you no longer ctrl+c into a dead terminal
Find/Down:
+Better no-key error message
+Downloads with ID for exporting
Options:
+p is now prompt for deletion instead of playing media
Export:
+select songs like play
+pastes them all to output fat command
+works with both url's in filenames AND yt-dlp id's, as long as they are surrounded by []

diff --git a/utmp b/utmp
--- a/utmp
+++ b/utmp
@@ -6,45 +6,9 @@ what=$4
 
 trap 'echo -e "\033[0;31m Utmp stopped :::during::: unknown state\033[0;0m"; exit 1' SIGINT
 
+WDIR=$(dirname $0)
 if [ "X$mode" = "X" ]; then
-	cat << EOF
-utmp <mode> <key> [-p,-t] [-s]
-	DESC:
-		Utmp stands for Ultra Chad Music Player, and it tries it's best to be that.
-		Utmp only can do a couple things: play music, download or (crappily) find music, and tell you what it's downloaded so far.
-		It essentially has the same functionality as a Discord music bot, save for the fact it runs on your computer and (typically) permanently stores it's files.
-
-	TEXT COLORS:
-		green text is standard text, colored green to seperate from the terminal's white
-		orange text is a warning, either the program had to do extra work, or an error that will not stop utmp from running
-		red text is fatal error text, the program will stop after showing you red text
-		white text is utmp telling big brain people what it's doing, or are generated as an error by utmp's commands
-
-	INPUTS:
-		<mode> : can be set to each of the following values:
-			list : show all songs in library (inside ~/utmp/ folder)
-			find : use key as \033[0;32msearch query\033[0;0m on youtube to find videos
-			down : use key as a \033[0;32link\033[0;0m to directly download videos
-			play : play videos from library using their indexes
-						 key 0 would play the first song in library
-						 key 0,4,2 would play the first, fifth, and then third song in library
-						 key all would play every single song in the library, in a random order
-
-		<key> : what this needs to be changes based on <mode>
-			<mode> is list : <key> can be nothing, but if something it will be used as a search keyword, only returning results with that text
-			<mode> is find : <key> can be anything (but not nothing), and make sure you put quotes around the text if it has spaces
-			<mode> is down : <key> should be a url
-			<mode> is play : <key> should be a bunch of numbers seperated by commas
-
-	OPTIONS:
-		-p : Play downloaded video, if any. Only works with <mode> as 'find' or 'down'
-
-		-t : Play video like -p, and then prompt for deletion
-				 Recommended to use -t when using 'find' mode as Youtube may not always return what you wanted
-
-		-s : Use when downloading from a soundcloud link
-				 Always put at the end of argument list!
-EOF
+	$WDIR/utmp-desc
 	exit 1
 fi
 
@@ -74,8 +38,9 @@ if [ $mode = "list" ]; then
 	echo -e "\033[0;32m----------------------\033[0;0m"
 
 elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
-	[ -z "$key" ] && echo -e "\033[0;31mNeed <key> to search on Youtube!\033[0;0m" && exit 1
+	[ -z "$key" ] && echo -e "\033[0;31mNeed <key> to download/find from Youtube!\033[0;0m" && exit 1
 	#^ there is key OR I exit now
+
 	if [ $mode = "find" ]; then
 		echo -e "\033[0;32mSearching for '$key'...\033[0;0m"
 
@@ -83,11 +48,11 @@ elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
 
 		if [ "$what" = "-s" ] || [ "$opt" = "-s" ]; then
 			echo -e "\033[0;32m[-s] removed \"-f 139\" from command\033[0;0m"
-			echo "yt-dlp "$key" --default-search auto --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/%(title)s.%(ext)s\""
-			yt-dlp "$key" --default-search auto --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/%(title)s.%(ext)s"
+			echo "yt-dlp "$key" --default-search auto --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s\""
+			yt-dlp "$key" --default-search auto --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s"
 		else
-			echo "yt-dlp "$key" -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/%(title)s.%(ext)s\""
-			yt-dlp "$key" -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/%(title)s.%(ext)s"
+			echo "yt-dlp "$key" -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s\""
+			yt-dlp "$key" -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s"
 		fi
 	else
 		echo -e "\033[0;32mDownloading from '$key'...\033[0;0m"
@@ -96,17 +61,17 @@ elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
 
 		if [ "$what" = "-s" ] || [ "$opt" = "-s" ]; then
 			echo -e "\033[0;32m[-s] removed \"-f 139\" from command\033[0;0m"
-			echo "yt-dlp "$key" --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/%(title)s.%(ext)s\""
-			yt-dlp "$key" --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/%(title)s.%(ext)s"
+			echo "yt-dlp "$key" --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s\""
+			yt-dlp "$key" --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s"
 		else
-			echo "yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/%(title)s.%(ext)s\""
-			yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/%(title)s.%(ext)s"
+			echo "yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet -o \"$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s\""
+			yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet -o "$TEMPDIR/[%(id)s]  -  %(title)s.%(ext)s"
 		fi
 		#still force 1 download because we only move the 1 last download, not all downloaded
 	fi
 
 	name=$(ls -t $TEMPDIR | tail -1)
-	[ "$name" = "" ] && echo -e "\033[0;31mCould not find downloaded file!\033[0;0m" && echo -e "\033[0;32mDid you forget to use -s while dowloading or not have wifi?\033[0;0m" && exit 1
+	[ "$name" = "" ] && echo -e "\033[0;31mCould not find downloaded file!\033[0;0m" && echo -e "\033[0;32mDid you forget to use -s while dowloading or not have wifi?\033[0;0m" && trap - SIGINT && exit 1
 	echo -e "\033[0;32mDownloaded result as: $name\033[0;0m"
 
 	if [ "$what" = "-s" ] || [ "$opt" = "-s" ]; then
@@ -137,8 +102,6 @@ elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
 	echo "mv \"$TEMPDIR/$fname\" \"$DIR/$fname\""
 	mv "$TEMPDIR/$fname" "$DIR/$fname"
 
-	[ "$opt" = "-p" ] && ( echo -e "\033[0;32m[-p] Playing '$fname'\033[0;0m" && ffplay -i $DIR/$fname -showmode 1 -autoexit -volume 25 -loglevel fatal )
-
 	if [ "$opt" = "-t" ]; then
 		echo -e "\033[0;32m[-t] Playing '$fname'\033[0;0m"
 		echo "ffplay -i \"$DIR/$fname\" -showmode 1 -autoexit -volume 25 -loglevel fatal"
@@ -146,7 +109,9 @@ elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
 		trap 'echo -e "\033[0;31m Utmp stopped :::during::: file playback\033[0;0m"; exit 1' SIGINT
 
 		ffplay -i "$DIR/$fname" -showmode 1 -autoexit -volume 25 -loglevel fatal
+	fi
 
+	if [ "$opt" = "-t" ] || [ "$opt" = "-p" ]; then
 		read -r -p "Delete file? [N/y]: " inp
 		if [ "$inp" = "N" ]; then
 			echo -e "\033[0;32mWill not delete file\033[0;0m"
@@ -159,7 +124,7 @@ elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
 	fi
 
 elif [ $mode = "play" ]; then
-	[ -z "$key" ] && echo -e "\033[0;31mNeed <key> to play songs!\033[0;0m" && exit 1
+	[ -z "$key" ] && echo -e "\033[0;31mNeed <key> to play songs!\033[0;0m" && trap - SIGINT && exit 1
 
 	trap 'echo -e "\033[0;31m Utmp stopped :::during::: file playback\033[0;0m"; exit 1' SIGINT
 
@@ -200,7 +165,77 @@ elif [ $mode = "play" ]; then
 		rm $foundf
 	done
 
+elif [ $mode = "expo" ]; then
+	trap 'echo -e "\033[0;31m Utmp stopped :::during::: library export\033[0;0m"; exit 1' SIGINT
+	out="echo \"::UTMP LIBRARY IMPORT::\""
+
+	if [ "$key" = "all" ] || [ -z "$key" ]; then
+		echo -e "\033[0;33mExporting ALL songs!\033[0;0m"
+		queue=$(ls $DIR/{*.mp3,*.m4a} | tr " " "^" | sort -R)
+
+		for file in $queue; do
+			file=$(echo $file | tr "^" " ")
+
+			#cope with both yt-dlp ID's and full url's!
+			url=$(echo $file | sed 's#_#/#g')
+			#remove left side, remove right side
+			url=$(echo $url | sed 's#.*\[##g')
+			url=$(echo $url | sed 's#\].*##g')
+
+			if [ "$url" = "" ] || [ "$url" = "$file" ]; then
+				echo -e "\033[0;33m$file has no formatted url, skipping!\033[0;0m"
+			else
+				echo -e "\033[0;32mExport: $file \033[0;0m->\033[0;32m $url\033[0;0m"
+				out="$out && utmp down \"$url\" -p"
+				# echo $out
+			fi
+
+			((count++))
+		done
+		echo $out
+	fi
+
+	IFS=',' read -ra dexes <<< "$key"
+	echo -e "\033[0;32mPlaying songs: ${dexes[@]}\033[0;0m"
+	for index in ${dexes[@]}; do
+		foundf=/tmp/found.$$
+		echo 0 > $foundf
+		count=0
+		queue=$(ls $DIR/{*.mp3,*.m4a} | tr " " "^")
+
+		for file in $queue; do
+				file=$(echo $file | tr "^" " ")
+		    if [ $count = $index ]; then
+					cfile=$(echo $file | tr "^" " ")
+
+					#cope with both yt-dlp ID's and full url's!
+					url=$(echo $cfile | sed 's#_#/#g')
+					#remove left side, remove right side
+					url=$(echo $url | sed 's#.*\[##g')
+					url=$(echo $url | sed 's#\].*##g')
+
+					if [ "$url" = "" ] || [ "$url" = "$file" ] || [ "$url" = "$cfile" ]; then
+						echo -e "\033[0;33m$file has no formatted url, skipping!\033[0;0m"
+					else
+						echo -e "\033[0;32mExport: $file \033[0;0m->\033[0;32m $url\033[0;0m"
+						out="$out && utmp down \"$url\" -p"
+						# echo $out
+					fi
+
+					echo 1 > $foundf
+				fi
+				((count++))
+		done
+
+		found=$(cat $foundf)
+		[ $found -eq 0 ] && ( echo -e "\033[0;33mCannot export [$index]: File not found!\033[0;0m" )
+		rm $foundf
+	done
+	echo $out
+
 else
 	echo -e "\033[0;31mInvalid mode $mode!\033[0;0m"
+	trap - SIGINT
+	echo $out
 	exit 1
 fi
