Spaces don't matter anymore
Also use a temp dir for downloading so we never get confused
Change (hopefully) all ~/utmp to use a var path instead

diff --git a/utmp b/utmp
--- a/utmp
+++ b/utmp
@@ -14,7 +14,7 @@ utmp <mode> <key> [-p,-t]
 		green text is standard text, colored green to seperate from the terminal's white
 		orange text is a warning, either the program had to do extra work, or an error that will not stop utmp from running
 		red text is fatal error text, the program will stop after showing you red text
-		white text is utmp showing you what it's doing, or perhaps is generated as an error by utmp's commands
+		white text is utmp telling big brain people what it's doing, or are generated as an error by utmp's commands
 
 	INPUTS:
 		<mode> : can be set to each of the following values:
@@ -40,8 +40,10 @@ EOF
 	exit 1
 fi
 
-DIR=~/utmp/
+DIR=~/utmp
+TDIR=~/utmp/temp
 [ ! -d $DIR ] && ( echo "\033[0;32mno existing DIR, creating new directory!\033[0;0m" && mkdir $DIR )
+[ ! -d $TDIR ] && ( echo "\033[0;32mno existing TDIR, creating new directory!\033[0;0m" && mkdir $TDIR )
 
 echo ""
 
@@ -49,8 +51,11 @@ if [ $mode = "list" ]; then
 	echo -e "\033[0;32mCurrent Stored Library:\033[0;0m"
 	echo -e "\033[0;32mKeyword: $key\033[0;0m"
 	count=0
-	find ~/utmp -type f -name "*$key*.mp3" -print0 | while IFS= read -r -d '' file; do
-	    echo -e "\033[0;32m$count\033[0;0m : $(basename $file)"
+	# find ~/utmp -type f -name "*$key*.mp3" -print0 | while IFS= read -r -d '' file; do
+	queue=$(ls {*.mp3,*.m4a} | tr " " "_")
+	for file in $queue; do
+			file=$(echo $file | tr "_" " ")
+	    echo -e "\033[0;32m$count\033[0;0m : $(echo $file | sed 's/.*\///g')"
 			((count++))
 	done
 	echo -e "\033[0;32m----------------------\033[0;0m"
@@ -60,49 +65,49 @@ elif [ "$mode" = "find" ] || [ "$mode" = "down" ]; then
 	#^ there is key OR I exit now
 	if [ $mode = "find" ]; then
 		echo -e "\033[0;32mSearching for '$key'...\033[0;0m"
-		echo yt-dlp $key -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet
-		yt-dlp $key -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet
+		echo "yt-dlp "$key" -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet -o \"$TDIR/%(title)s.%(ext)s\""
+		yt-dlp "$key" -f 139 --default-search auto --max-downloads 1 --abort-on-error --quiet -o "$TDIR/%(title)s.%(ext)s"
 	else
 		echo -e "\033[0;32mDownloading from '$key'...\033[0;0m"
-		echo yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet
-		yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet
+		echo "yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet -o \"$TDIR/%(title)s.%(ext)s\""
+		yt-dlp "$key" -f 139 --max-downloads 1 --abort-on-error --quiet -o "$TDIR/%(title)s.%(ext)s"
 		#still force 1 download because we only move the 1 last download, not all downloaded
 	fi
 
-	name=$(ls -t | tail -1)
-	fname=$(echo $name | sed -e 's/ /\_/g')
-	echo -e "\033[0;32mDownloaded result: $name\033[0;0m"
-	echo -e "\033[0;32m               as: $fname\033[0;0m"
-
-	echo "mv \"$name\" ~/utmp/$fname"
-	mv "$name" ~/utmp/$fname
+	name=$(ls $TDIR -t | tail -1)
+	[ "$TDIR" = "$name"  ] && [ echo -e "\033[0;31mCould not find downloaded file!\033[0;0m" && exit 1 ]
+	echo -e "\033[0;32mDownloaded result as: $name\033[0;0m"
 
 	echo -e "\033[0;32mConverting result to mp3...\033[0;0m"
-	echo ffmpeg -i ~/utmp/$fname ~/utmp/$(echo $fname | sed -e 's,.m4a,.mp3,g') -loglevel fatal -y
-	ffmpeg -i ~/utmp/$fname ~/utmp/$(echo $fname | sed -e 's,.m4a,.mp3,g') -loglevel fatal -y
+	fname=$(echo $name | sed -e 's,.m4a,.mp3,g')
+	echo "ffmpeg -i \"$TDIR/$name\" \"$TDIR/$fname\" -loglevel fatal -y"
+	ffmpeg -i "$TDIR/$name" "$TDIR/$fname" -loglevel fatal -y
 	#-y to automatically overwrite files without prompting
-	echo -e "\033[0;32mConverted to: $(echo $fname | sed -e 's,.m4a,.mp3,g')\033[0;0m"
+	echo -e "\033[0;32mConverted to: $fname\033[0;0m"
 
-	rm ~/utmp/$fname
+	echo "rm \"$TDIR/$name\""
+	rm "$TDIR/$name"
 	echo -e "\033[0;32mRemoved old file\033[0;0m"
 
-	fname=$(echo $fname | sed -e 's,.m4a,.mp3,g')
 	echo -e "\033[0;32mDone downloading!\033[0;0m"
 
-	[ "$opt" = "-p" ] && ( echo -e "\033[0;32m[-p] Playing '$fname'\033[0;0m" && ffplay -i ~/utmp/$fname -showmode 1 -autoexit -volume 25 -loglevel fatal )
+	echo "mv \"$TDIR/$fname\" \"$DIR/$fname\""
+	mv "$TDIR/$fname" "$DIR/$fname"
+
+	[ "$opt" = "-p" ] && ( echo -e "\033[0;32m[-p] Playing '$fname'\033[0;0m" && ffplay -i $DIR/$fname -showmode 1 -autoexit -volume 25 -loglevel fatal )
 
 	if [ "$opt" = "-t" ]; then
 		echo -e "\033[0;32m[-t] Playing '$fname'\033[0;0m"
-		echo ffplay -i ~/utmp/$fname -showmode 1 -autoexit -volume 25 -loglevel fatal
-		ffplay -i ~/utmp/$fname -showmode 1 -autoexit -volume 25 -loglevel fatal
+		echo "ffplay -i \"$DIR/$fname\" -showmode 1 -autoexit -volume 25 -loglevel fatal"
+		ffplay -i "$DIR/$fname" -showmode 1 -autoexit -volume 25 -loglevel fatal
 
 		read -r -p "Delete file? [N/y]: " inp
 		if [ "$inp" = "N" ]; then
 			echo -e "\033[0;32mWill not delete file\033[0;0m"
 		else
 			echo -e "\033[0;33mDeleting $fname!\033[0;0m"
-			echo rm ~/utmp/$fname
-			rm ~/utmp/$fname
+			echo "rm \"$DIR/$fname\""
+			rm "$DIR/$fname"
 			echo -e "\033[0;32mDone\033[0;0m"
 		fi
 	fi
@@ -112,13 +117,14 @@ elif [ $mode = "play" ]; then
 
 	if [ "$key" = "all" ]; then
 		echo -e "\033[0;33mPlaying ALL songs!\033[0;0m"
-		queue=$(find ~/utmp -type f -name "*.mp3" | sort -R)
+		queue=$(ls {*.mp3,*.m4a} | tr " " "_" | sort -R)
 
 		for file in $queue; do
-				echo -e "\033[0;32mPlaying $file\033[0;0m"
-				echo ffplay -i $file -showmode 1 -autoexit -volume 25 -loglevel fatal
-				ffplay -i $file -showmode 1 -autoexit -volume 25 -loglevel fatal
-				((count++))
+			file=$(echo $file | tr "_" " ")
+			echo -e "\033[0;32mPlaying $file...\033[0;0m"
+			echo "ffplay -i \"$file\" -showmode 1 -autoexit -volume 25 -loglevel fatal"
+			ffplay -i "$file" -showmode 1 -autoexit -volume 25 -loglevel fatal
+			((count++))
 		done
 	fi
 
@@ -128,11 +134,14 @@ elif [ $mode = "play" ]; then
 		foundf=/tmp/found.$$
 		echo 0 > $foundf
 		count=0
-		find ~/utmp -type f -name "*.mp3" -print0 | while IFS= read -r -d '' file; do
+		queue=$(ls {*.mp3,*.m4a} | tr " " "_")
+
+		for file in $queue; do
+				file=$(echo $file | tr "_" " ")
 		    if [ $count = $index ]; then
 					echo -e "\033[0;32mPlaying [$index]: $file\033[0;0m"
-					echo ffplay -i $file -showmode 1 -autoexit -volume 25 -loglevel fatal
-					ffplay -i $file -showmode 1 -autoexit -volume 25 -loglevel fatal
+					echo "ffplay -i \"$file\" -showmode 1 -autoexit -volume 25 -loglevel fatal"
+					ffplay -i "$file" -showmode 1 -autoexit -volume 25 -loglevel fatal
 					echo 1 > $foundf
 				fi
 				((count++))
